# Generated by Django 5.2.17 on 2026-09-14 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctoral', 'Doctoral')], default='bachelor', max_length=20)),
                ('field_of_study', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='skill',
        ),
    ]
