# Generated by Django 5.2.17 on 2026-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='started_at',
        ),
        migrations.AddField(
            model_name='education',
            name='education_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('SMA/SMK', 'SMA/SMK'), ('D3', 'Diploma (D3)'), ('S1', 'Sarjana (S1)'), ('S2', 'Magister (S2)'), ('S3', 'Doktor (S3)')], default='S1', max_length=50),
        ),
    ]
