# Generated by Django 5.2.17 on 2026-09-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_project_starred_by_alter_project_project_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=50),
        ),
    ]
